services:
  api:
    image: ghcr.io/obaidurrehmankhan/nestjs-docker-postgres-onprem:latest
    container_name: onprem_api
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_SSL: "true"
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: onprem_db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d appdb" ]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:1.25-alpine
    container_name: onprem_nginx
    depends_on:
      api:
        condition: service_started
    ports:
      - "80:80"
      - "443:443" # allow HTTPS
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # mount TLS certs from host
    restart: always

volumes:
  pgdata:
